# Generated by Django 5.2 on 2026-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_max', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
